INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',2,322,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',13,NULL,8146);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',17,717,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',21,NULL,4541);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',22,543,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',39,NULL,2720);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',44,345,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',51,NULL,8330);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',52,755,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',58,NULL,1850);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',73,506,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',87,NULL,1670);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',89,132,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',2,NULL,62);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',13,599,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',17,NULL,1661);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',21,385,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',22,NULL,1071);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',39,288,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',44,NULL,7600);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',51,220,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',52,NULL,5422);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',58,794,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',73,NULL,5134);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',87,999,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',89,NULL,8458);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',2,436,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',13,NULL,8557);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',17,419,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',21,NULL,5748);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',22,604,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',39,NULL,1599);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',44,923,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',51,NULL,3296);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',52,800,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',58,NULL,2575);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',73,151,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',87,NULL,7394);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',89,900,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',2,NULL,9221);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',13,816,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',17,NULL,1723);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',21,748,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',22,NULL,6212);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',39,287,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',44,NULL,7333);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',51,550,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',52,NULL,2584);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',58,616,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',73,NULL,4510);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',87,958,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',89,NULL,1453);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',2,490,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',13,NULL,8387);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',17,658,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',21,NULL,7392);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',22,8,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',39,NULL,2236);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',44,345,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',51,NULL,8197);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',52,606,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',58,NULL,738);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',73,774,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',87,NULL,8003);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',89,96,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',2,NULL,6878);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',13,824,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',17,NULL,5426);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',21,970,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',22,NULL,9182);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',39,636,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',44,NULL,5702);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',51,570,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',52,NULL,7287);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',58,453,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',73,NULL,3376);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',87,918,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',89,NULL,4226);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',2,701,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',13,NULL,552);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',17,969,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',21,NULL,3026);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',22,231,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',39,NULL,8918);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',44,462,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',51,NULL,4084);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',52,129,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',58,NULL,2303);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',73,556,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',87,NULL,5761);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',89,505,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',2,NULL,1902);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',13,887,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',17,NULL,2573);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I consider this news to be spam therefore it should be banned in my opinion.',21,84,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('If we accept comments like this we might be facing law problems.',22,NULL,2205);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('This article has been reported for racism, unsure if I should act on it.',39,674,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I do not see any reason as to how this is racism, it should be disregarded.',44,NULL,4134);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I agree with jonhy97. I consider it to be offensive to many people therefore it should be banned.',51,790,NULL);
INSERT INTO ModeratorComments (text, creator_user_id, news_id, comment_id) VALUES ('I will report to an admin',52,NULL,2663);
